### ISSUE TITLE
faster way to determine catalog id?

### ISSUE THREAD

**Issue by edsu** [umd-mith/hathilda#2]
hathilda's JSON-LD currently uses a volumes Handle as the subject URI. So you give hathilda a volume identifier like `ucm.5305727634`  and it returns the JSON-LD for that volume, which uses http://hdl.handle.net/2027/ucm.5305727634 as the subject URI. 

hathilda currently uses the [HathiTrust Bibliographic API](http://www.hathitrust.org/bib_api) to get a MARCXML record for the volume, and picks various things out of the MARC record. The Bibliographic API does not allow for lookup by Volume ID so it first gets the web page for a volume (e.g. [http://babel.hathitrust.org/cgi/pt?id=ucm.5305727634](http://babel.hathitrust.org/cgi/pt?id=ucm.5305727634)) and scrapees out the link to the catalog (e.g. [http://catalog.hathitrust.org/Record/009649975](http://catalog.hathitrust.org/Record/009649975)), which it pulls the Record ID out of, to use to talk to the Bibliographic API (e.g. [http://catalog.hathitrust.org/api/volumes/full/recordnumber/009649975](http://catalog.hathitrust.org/api/volumes/full/recordnumber/009649975)). 

The trouble with this is that the scraping takes a while, sometimes up to 10 seconds. This slows down the process of getting JSON-LD for a volume significantly. Perhaps it's possible to get the MARC or MODS for a volume ID from the [HathiTrust Data API](http://www.hathitrust.org/data_api) instead?

**Comment by billdueber** [comment]
Wait -- I think I see what you're trying to do. Try using a URL of the form:

http://catalog.hathitrust.org/Record/HTID/mdp.39015028735747.xml

Undocumented, but not going away anytime soon, and I can work to get it on the list of Things We Support.

**Comment by edsu** [comment]
Oh nice! That looks like it will be very handy.

**Comment by edsu** [comment]
fixed in [d695ea4e91b6ef5e10630702b40a42b3412db903]

**Comment by billdueber** [comment]
Also, the bibAPI totally allows lookup by hathitrust id:

http://catalog.hathitrust.org/api/volumes/full/htid/mdp.39015028735747.json

See the "valid ID types" a few inches down on http://www.hathitrust.org/bib_api

**Comment by edsu** [comment]
Yes, that's what i started using! Thanks.
